services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://whoami.your-dns.com'
      - caddy_ingress_network=caddy

networks:
  caddy:
    external: true
